### ISSUE TITLE
`FileNotFoundError` because of bad call to `subprocess.run` by `molecule`

### ISSUE THREAD

**Issue by colobas** [ansible-community/ansible-compat#118]
`molecule`'s login command calls `exec` from `ansible_compat/runtime.py`. This function calls `subprocess.run` with a variable `args`, which is one of the arguments to `exec`. However, if `args` is a string with spaces, which is the case for `molecule`'s login call, `subprocess.run` raises a `FileNotFoundError`. e.g.:

```
Traceback (most recent call last):
  File "/usr/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/molecule/command/login.py", line 166, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "/usr/lib/python3.10/site-packages/molecule/command/base.py", line 149, in execute_subcommand
    return command(config).execute()
  File "/usr/lib/python3.10/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/molecule/command/login.py", line 101, in execute
    self._get_login(hostname)
  File "/usr/lib/python3.10/site-packages/molecule/command/login.py", line 146, in _get_login
    app.runtime.exec(cmd)
  File "/usr/lib/python3.10/site-packages/ansible_compat/runtime.py", line 138, in exec
    result = run_func(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/env docker exec -e COLUMNS=88 -e LINES=29 -e TERM=bash -e TERM=xterm -ti molecule-minio-ubuntu1804 bash'
```

I've obviously tried copy pasting the underlying command it's trying to run and it works. I think maybe `subprocess.run` needs to be called with `shell=True` for this to work? Or the `args` variable has to be a list rather than a string?

I'm on archlinux, these are the versions of the relevant packages:
```
$ molecule --version
molecule 3.6.1 using python 3.10 
    ansible:2.12.2
    delegated:3.6.1 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
    podman:1.1.0 from molecule_podman requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
```

**Comment by colobas** [comment]
Identified as a `molecule` regression here: https://github.com/ansible-community/molecule/issues/3435

Closing.
